Change/task5
TetianaHarkusha/learning_phpoop pull request #3
Opened 2022-10-04 17:56 UTC by TetianaHarkusha

2022-10-06 18:41 UTC, R11baka commented on task5/Models/User.php
> +            $this->age = $this->age;
а зачем эта строчка ?

2022-10-06 18:41 UTC, R11baka commented on task5/Models/User.php
> +        if ($age < 18) {
18 вынести в константу. + назови константу MIN_AGE

2022-10-06 21:44 UTC, TetianaHarkusha commented on task5/Models/User.php
> +            $this->age = $this->age;
Протупила, исправила

2022-10-06 21:44 UTC, TetianaHarkusha commented on task5/Models/User.php
> +        if ($age < 18) {
Вынесла

2022-10-07 06:45 UTC, TetianaHarkusha commented on task5/Models/Employee.php
> +        return ($this->age > 18)? true: false;
Здесь тоже заменила 18 константой

2022-10-07 11:57 UTC, R11baka requested changes
Добавь еще 
`declare(strict_types=1);`
чтоб включить типизацию

2022-10-07 17:37 UTC, merged